services:
  dev:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///data.db
      - SECRET_KEY=supersecretkey
    command: python run.py
